{"metadata":{"title":"OpenAIError.apiError(_:)","symbolKind":"case","externalID":"s:9OpenAIKit0A7AIErrorO8apiErroryAcA8APIErrorVcACmF","roleHeading":"Case","role":"symbol","modules":[{"name":"OpenAIKit"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apiError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"APIError","preciseIdentifier":"s:9OpenAIKit8APIErrorV","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"variants":[{"paths":["\/documentation\/openaikit\/openaierror\/apierror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/OpenAIKit\/documentation\/OpenAIKit","doc:\/\/OpenAIKit\/documentation\/OpenAIKit\/OpenAIError"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiError"},{"kind":"text","text":"("},{"identifier":"doc:\/\/OpenAIKit\/documentation\/OpenAIKit\/APIError","kind":"typeIdentifier","preciseIdentifier":"s:9OpenAIKit8APIErrorV","text":"APIError"},{"kind":"text","text":")"}],"platforms":["Linux"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/OpenAIKit\/documentation\/OpenAIKit\/APIError","type":"reference","isActive":true},{"type":"text","text":" containing error details"}]}],"name":"error"}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This case wraps the structured error response from OpenAIâ€™s API,"},{"type":"text","text":" "},{"type":"text","text":"providing detailed information about what went wrong."}]},{"anchor":"Example","text":"Example","level":2,"type":"heading"},{"code":["do {","    let completion = try await openAI.completions.create(","        model: \"gpt-3.5-turbo\",","        messages: messages,","        maxTokens: 5000 \/\/ Too high","    )","} catch OpenAIError.apiError(let apiError) {","    print(\"Error type: \\(apiError.error.type ?? \"unknown\")\")","    print(\"Error message: \\(apiError.error.message)\")","    if let param = apiError.error.param {","        print(\"Problem parameter: \\(param)\")","    }","}"],"type":"codeListing","syntax":"swift"},{"style":"note","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/OpenAIKit\/documentation\/OpenAIKit\/APIError"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/OpenAIKit\/documentation\/OpenAIKit\/APIErrorDetail"}],"type":"paragraph"}],"name":"See Also","type":"aside"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/OpenAIKit\/documentation\/OpenAIKit\/OpenAIError\/apiError(_:)"},"kind":"symbol","abstract":[{"type":"text","text":"An error response was received from the OpenAI API."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://OpenAIKit/documentation/OpenAIKit":{"kind":"symbol","abstract":[{"text":"A powerful, type-safe Swift SDK for the OpenAI API with support for all major endpoints and platforms.","type":"text"}],"identifier":"doc:\/\/OpenAIKit\/documentation\/OpenAIKit","role":"collection","title":"OpenAIKit","url":"\/documentation\/openaikit","type":"topic"},"doc://OpenAIKit/documentation/OpenAIKit/OpenAIError":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenAIError"}],"identifier":"doc:\/\/OpenAIKit\/documentation\/OpenAIKit\/OpenAIError","url":"\/documentation\/openaikit\/openaierror","title":"OpenAIError","navigatorTitle":[{"kind":"identifier","text":"OpenAIError"}],"role":"symbol","abstract":[{"text":"The primary error type for all OpenAI API interactions.","type":"text"}],"type":"topic","kind":"symbol"},"doc://OpenAIKit/documentation/OpenAIKit/APIError":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIError"}],"identifier":"doc:\/\/OpenAIKit\/documentation\/OpenAIKit\/APIError","title":"APIError","url":"\/documentation\/openaikit\/apierror","navigatorTitle":[{"kind":"identifier","text":"APIError"}],"role":"symbol","type":"topic","abstract":[{"text":"A structured error response from the OpenAI API.","type":"text"}],"kind":"symbol"},"doc://OpenAIKit/documentation/OpenAIKit/APIErrorDetail":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIErrorDetail"}],"identifier":"doc:\/\/OpenAIKit\/documentation\/OpenAIKit\/APIErrorDetail","title":"APIErrorDetail","url":"\/documentation\/openaikit\/apierrordetail","navigatorTitle":[{"kind":"identifier","text":"APIErrorDetail"}],"role":"symbol","type":"topic","abstract":[{"text":"Detailed error information from the OpenAI API.","type":"text"}],"kind":"symbol"},"doc://OpenAIKit/documentation/OpenAIKit/OpenAIError/apiError(_:)":{"title":"OpenAIError.apiError(_:)","identifier":"doc:\/\/OpenAIKit\/documentation\/OpenAIKit\/OpenAIError\/apiError(_:)","url":"\/documentation\/openaikit\/openaierror\/apierror(_:)","type":"topic","kind":"symbol","abstract":[{"text":"An error response was received from the OpenAI API.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apiError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"APIError","kind":"typeIdentifier","preciseIdentifier":"s:9OpenAIKit8APIErrorV"},{"text":")","kind":"text"}]}}}